### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by cferenba** [USRSE/logo#1]
@vsoch:  the rse-logo.svg looks great, thanks for creating it!

I notice that the other versions of the logo are missing a couple of features relative to the base version:  the stripes are missing on the right side, as is the white shadow behind the maroon square.  Could you fix these when you get a chance?

**Comment by vsoch** [comment]
Missing, or improved?

All jokes aside, it's intentionally done as a simplified version, and I also don't have the vector / inkscape skills to figure out how to do a (professionally done) curved line. Maybe someone else has the skills / software? Personally, I like the version that I made better, because it is much simpler and still gives a sense of the US flag behind the letter.

**Comment by vsoch** [comment]
Also, the shadows are removed also in favor of simplicity. If you look at logos that are professional and stand the test of time, they are overwhelmingly simple.  They can come down to a single letter with a few colors, and generally without extra shadow or depth.

**Comment by vsoch** [comment]
This seems like something that should be discussed by the general community - open to all participants of usrse.

**Comment by cferenba** [comment]
Good points.  I agree simplicity makes sense.  It just looks weirdly asymmetric to me to have stripes on one side and not the other.

And I agree, a wider discussion makes sense.  Maybe it's best to come up with a specific proposal to run by the larger group.  Let me think on this a bit more...

**Comment by vsoch** [comment]
I think @cosden mentioned there is a steering committee? it might make sense for that group to come up with an idea for a method, share with the community for feedback, and then make it so! For example, it could be some kind of vote on features, and then a re-design. The hard part of course is finding someone with the design chops and software to do it. I was really good with Photoshop back in the day (back when you could actually own the disks) but I've never taken to Inkscape, at least for more sophisticated stuffs.

**Comment by cosden** [comment]
We had a vote in slack a few months ago when @cferenba made the first 3 options of the new logo.  There were a few less people back then!  I think you've hit the nail on the head, @vsoch.  I think we all want this to be a community driven organization, but we need to have a method for how to make decisions and then some kind of agreement to move forward as a group.  I think I read it somewhere else tonight, and I think you said it @vsoch, but having content and a starting point is so much better than having nothing.  We'll figure this out, I'm sure.
